### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'name'" because experiment_tracker isn't set?

### ISSUE THREAD

**Issue by Taytay** [zenml-io/template-e2e-batch#8]
It looks like the default installation of this project doesn't include an experiment tracker, which causes it to error out when I run `python run.py`. I presume I should install one, but didn't see this mentioned in the docs.

Stack trace:

.../e2e_batch/steps/training/model_evaluator.py:34 in <module>        │
│                                                                                                  │
│    31 experiment_tracker = Client().active_stack.experiment_tracker                              │
│    32                                                                                            │
│    33                                                                                            │
│ ❱  34 @step(experiment_tracker=experiment_tracker.name)                                          │
│    35 def model_evaluator(                                                                       │
│    36 │   model: ClassifierMixin,                                                                │
│    37 │   dataset_trn: pd.DataFrame,                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by avishniakov** [comment]
Hey @Taytay , 
Installation of required stack components is done via make, if you want. Specifically tracker is installed with [this](https://github.com/zenml-io/template-e2e-batch/blob/7a049677bd8ba214e01c6f068c92c5fe431a5fac/template/Makefile#L16).

The instructions on how to run it are given after you clone temlate in the same CLI session. But you are right, it is not part of the README.md as of now - I'll update this part.
